from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent
DB_PATH = BASE_DIR / "keyboard.db"
REPORT_DIR = BASE_DIR / "reports"

SESSION_IDLE_MINUTES = 30
ACTIVE_WINDOW_SECONDS = 60
RECENT_INTENSITY_MINUTES = 60
HIGH_INTENSITY_KEYS_PER_MIN = 80
FATIGUE_SESSION_RISK_MINUTES = 90

UI_REFRESH_MS = 5000
STATS_CACHE_REFRESH_MINUTES = 60

DAILY_REPORT_HOUR = 18
DAILY_REPORT_MINUTE = 30

